version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_URI
      - echo Getting CodeArtifact token...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain my-domain --query authorizationToken --output text)
      - export CODEARTIFACT_URL=https://my-domain-${AWS_ACCOUNT_ID}.d.codeartifact.${AWS_REGION}.amazonaws.com/pypi/python-store/simple/

  build:
    commands:
      - echo Building Docker image...
      - docker build \
          --build-arg CODEARTIFACT_URL=$CODEARTIFACT_URL \
          --build-arg CODEARTIFACT_TOKEN=$CODEARTIFACT_AUTH_TOKEN \
          -t $REPO_URI:$IMAGE_TAG .
      - echo Pushing image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"my-app-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
